### ISSUE TITLE
Table support dataSource

### ISSUE THREAD

**Issue by Binh-Boong** [thien-do/moai#22]
- New feature:
![image](https://user-images.githubusercontent.com/18264968/103528528-b6092880-4eb6-11eb-9044-4315fd3d5340.png)
 same antd :>3
![image](https://user-images.githubusercontent.com/18264968/103529020-8575be80-4eb7-11eb-9ea7-4e2ae3821954.png)

- Current: I don't like index !!!
![image](https://user-images.githubusercontent.com/18264968/103528761-15673880-4eb7-11eb-85f3-237f4046729f.png)

**Comment by thien-do** [comment]
Hi @Binh-Boong :D thanks for the suggestion. I must say "I don't like index !!!" is not really a compelling argument to me. However this is still a better solution than using index atm (I always think the "rowsLength" sounds wrong after all).

So we implemented this in the latest version of Moai:
- For the exact interface, see: https://github.com/thien-do/moai/blob/4c769d1df5ad29504ff2626ded9e5053293dc40f/core/src/table/table.tsx#L10-L12
- For a simple usage (accessor style), see: https://github.com/thien-do/moai/blob/4c769d1df5ad29504ff2626ded9e5053293dc40f/core/src/table/table.stories.tsx#L12-L20
- For a complex usage (custom render), see: https://github.com/thien-do/moai/blob/4c769d1df5ad29504ff2626ded9e5053293dc40f/site/components/gallery/table.tsx#L103-L110
