### ISSUE TITLE
ButtonMenu should be close after user select

### ISSUE THREAD

**Issue by dangbt** [thien-do/moai#24]
![Screen Shot 2021-01-07 at 2 57 32 PM](https://user-images.githubusercontent.com/22491666/103866686-bdb80f80-50f8-11eb-8937-9e749db9d7fd.png)

**Comment by thien-do** [comment]
what's wrong here? Is that the outline looks bad

**Comment by thien-do** [comment]
Right

**Comment by thien-do** [comment]
Actually it is
