### ISSUE TITLE
Support tag color.

### ISSUE THREAD

**Issue by Binh-Boong** [thien-do/moai#27]
- orange, violet, light...

![image](https://user-images.githubusercontent.com/18264968/105317147-75b6e380-5bf4-11eb-9fb1-21a7ffea7c81.png)
![image](https://user-images.githubusercontent.com/18264968/105317423-c0d0f680-5bf4-11eb-80c4-5699853f7af0.png)
![image](https://user-images.githubusercontent.com/18264968/105317556-eb22b400-5bf4-11eb-843e-eca4dc568c29.png)

**Comment by thien-do** [comment]
Done
